    
sudo: required
dist: trusty

language: cpp
compiler:
  - clang
  - gcc
before_script:
    - wget https://root.cern.ch/download/root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
    - tar xzvf root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
    - source root/bin/thisroot.sh
script:
    - mkdir build
    - cd build
    - cmake .. && make
    - make install
    - cd ..
    - source PAF_setup.sh
    

after_script:
   - cd test/ 
   - mkdir build 
   - cd build
   - cmake -DCMAKE_BUILD_TYPE=Debug .. 
   - make && ctest