language: cpp
compiler:
  - clang
  - gcc
before_script:
    - wget https://root.cern.ch/download/root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
    - tar xzvf root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
    - source root/bin/thisroot.sh
script:
    - mkdir build
    - cd build
    - cmake .. && make
sudo: required
dist: trusty
