/*========================================================
  SelB selector

  This file was automatically generated by PAF

  As a rule, you should leave the comments with a pattern
  like '//%SOMETEXT%' unmodified to let the paf help tools
  work
  ========================================================*/

// Includes
#include "SelB.h"

#include "TLorentzVector.h"
#include <vector>

ClassImp(SelB);

/*-------------------------------------------
  SelB class constructor. Make sure you initialise all the pointers to 0
  ---------------------------------------- */
SelB::SelB() : PAFChainItemSelector() 
{
  // Leave the following lines if you intend to use
  // the paf tools to add objects to your anlysis
  // %STARTCONSTRUCTOR%
  // %ENDCONSTRUCTOR%


}


/*-------------------------------------------
  Initialise() holds the code executed at the begining and before
  the any event is processed. It will for example contain the initialization
  of histograms, output trees, etc..
  ---------------------------------------- */
void SelB::Initialise() 
{

  // Leave the following lines if you intend to use
  // the paf tools to add objects to your anlysis
  // %STARTHISTOINIT%
  // %ENDHISTOINIT%
  
}



/*-------------------------------------------
  InsideLoop() holds the code that is executed once every event is read.
  Here you will, for example, read the event variables, process them and 
  fill the histograms.
  ---------------------------------------- */
void SelB::InsideLoop() 
{

  // There are many ways to read a variable in the tree. For example:
  // float some_variable = Get<float>("some_variable");

  // + Recover the TLorentzVector passed around by selector SelA
  //   and check that it has the value sent
  PAF_INFO("SelB", "Getting TLorentzVector");
  TLorentzVector v = GetParam<TLorentzVector>("V");
  if (v.X() != 1 ||
      v.Y() != 1 ||
      v.Z() != 1 ||
      v.E() != -1)
    PAF_ERROR("SelB", "TLorentzVector different from expected");
      
  // + Recover the vector<TLorentzVector> passed around by selector SelA
  //   and check that it has the value sent
  PAF_INFO("SelB", "Getting std vector");
  std::vector<TLorentzVector> s = GetParam< std::vector<TLorentzVector> >("S");
  if (s[0].X() != -1 ||
      s[0].Y() != -1 ||
      s[0].Z() != -1 ||
      s[0].E() != 1)
    PAF_ERROR("SelB", "std::vector<TLorentzVector> different from expected");
  

}



/*-------------------------------------------
  Summary() holds the code executed after all the events have been processed.
  It will, for example, produce the final yields or a summary of the results
  processed.
  ---------------------------------------- */
void SelB::Summary()
{

  // Leave the following lines if you intend to use
  // the paf tools to add objects to your anlysis
  // %STARTSUMMARY%
  // %ENDSUMMARY%

}
