/*========================================================
  SelB selector

  This file was automatically generated by PAF

  As a rule, you should leave the comments with a pattern
  like '//%SOMETEXT%' unmodified to let the paf help tools
  work
  ========================================================*/
#pragma once

// Includes
#include "PAFChainItemSelector.h"


// Your selector class
class SelB : public PAFChainItemSelector 
{
 public:
  // Constructor and destructor
  SelB();
  virtual ~SelB() {}
  
  // Mandatory methods
  virtual void Initialise();
  virtual void InsideLoop();
  virtual void Summary();


  // You would tipically add here your protected methods
  // and data members

 protected:

  // You would tipically add here your protected methods
  // and data members

  // Leave the following lines if you intend to use
  // the paf tools to add objects to your analysis
  // %STARTDATAMEMBERS%
  // %ENDDATAMEMBERS%
  
  ClassDef(SelB,0);
};
