/*========================================================
  SelA selector

  This file was automatically generated by PAF

  As a rule, you should leave the comments with a pattern
  like '//%SOMETEXT%' unmodified to let the paf help tools
  work
  ========================================================*/

// Includes
#include "SelA.h"

#include "TLorentzVector.h"

ClassImp(SelA);

/*-------------------------------------------
  SelA class constructor. Make sure you initialise all the pointers to 0
  ---------------------------------------- */
SelA::SelA() : PAFChainItemSelector() 
{
  // Leave the following lines if you intend to use
  // the paf tools to add objects to your anlysis
  // %STARTCONSTRUCTOR%
  // %ENDCONSTRUCTOR%


}


/*-------------------------------------------
  Initialise() holds the code executed at the begining and before
  the any event is processed. It will for example contain the initialization
  of histograms, output trees, etc..
  ---------------------------------------- */
void SelA::Initialise() 
{

  // Leave the following lines if you intend to use
  // the paf tools to add objects to your anlysis
  // %STARTHISTOINIT%
  // %ENDHISTOINIT%
  
}



/*-------------------------------------------
  InsideLoop() holds the code that is executed once every event is read.
  Here you will, for example, read the event variables, process them and 
  fill the histograms.
  ---------------------------------------- */
void SelA::InsideLoop() 
{

  // There are many ways to read a variable in the tree. For example:
  // float some_variable = Get<float>("some_variable");

  // + Create a TLorentzVector and a std::vector of TLorentzVectors
  PAF_INFO("SelA", "Creating TLorentzVector");
  TLorentzVector v(1,1,1,-1);

  PAF_INFO("SelA", "Creating std vector");
  TLorentzVector v2(-1,-1,-1,1);
  std::vector<TLorentzVector> s;
  s.push_back(v2);

  // + Pass the TLorentzVector and the vector around
  PAF_INFO("SelA", "Passing TLorentzVector");
  SetParam("V", v);

  PAF_INFO("SelA", "Passing std vector");
  SetParam("S", s);
}



/*-------------------------------------------
  Summary() holds the code executed after all the events have been processed.
  It will, for example, produce the final yields or a summary of the results
  processed.
  ---------------------------------------- */
void SelA::Summary()
{

  // Leave the following lines if you intend to use
  // the paf tools to add objects to your anlysis
  // %STARTSUMMARY%
  // %ENDSUMMARY%

}
