/*========================================================
  ChainedSelectorWithVectors project.
  (This file was initially automatically generated by PAF)
  
  This is the main macro of an example on how to build
  chained selectors that pass information among then using
  objects of non basic types.
  The project has 2 selectors:
  * SelA creates a TLorentzVector and an std::vector of
    TLorentzVector's
  * SelB finds the parameters passed and checks they are
    the same as those passed by SelA
  The main addition is the file LinkDef.h file in 
  packages/SelA. Some more information in the PAF tutorials
  "4 Parameter passing":
  http://www.hep.uniovi.es/PAF/home/tutorials/4-parameter-passing/

  ========================================================*/

void ChainedSelectorWithVectors() {

  // (1) Create the PAF project. 
  // By default this would the PROOF Lite environment
  // Other options:
  // + Sequential:    new PAFProject(new PAFSequentialEnvironmen())
  // + PROOF Lite:    new PAFProject(new PAFPROOFLiteEnvironment())
  // + PoD:           new PAFProject(new PAFPoDEnvironmen())
  // + PROOF Cluster: new PAFProject(new PAFPROOFClusterEnvironmen())
  // + PROOF Cloud:   new PAFProject(new PAFPROOFCloudEnvironmen())
  //PAFProject* myProject = new PAFProject(new PAFSequentialEnvironment());
  PAFProject* myProject = new PAFProject(new PAFPROOFLiteEnvironment());
  //PAFProject* myProject = new PAFProject(new PAFPoDEnvironment(10));
  

  // (2) Define the data files to be used.
  // Select the files to be analysed and replicate the line below
  // as needed
  myProject->AddDataFile("You have to specify the input file");

  
  // (3) Define the name of the selector to be used
  // Modify the line below to specify the name of your selector
  // To create a new selector you may use PAF tools:
  // $ paf createselector SelectorName
  // Adding 2 selectors A and B
  myProject->AddSelectorPackage("SelA");
  myProject->AddSelectorPackage("SelB");
  
  // (4) Run the project. 
  // This will start the processing
  myProject->Run();
}
