/*========================================================
  ChainedSelectorWithVectors project

  This file was automatically generated by PAF

  ========================================================*/

void ChainedSelectorWithVectors() {

  // (1) Create the PAF project. 
  // By default this would the PROOF Lite environment
  // Other options:
  // + Sequential:    new PAFProject(new PAFSequentialEnvironmen())
  // + PROOF Lite:    new PAFProject(new PAFPROOFLiteEnvironment())
  // + PoD:           new PAFProject(new PAFPoDEnvironmen())
  // + PROOF Cluster: new PAFProject(new PAFPROOFClusterEnvironmen())
  // + PROOF Cloud:   new PAFProject(new PAFPROOFCloudEnvironmen())
  PAFProject* myProject = new PAFProject(new PAFSequentialEnvironment());
  //PAFProject* myProject = new PAFProject(new PAFPROOFLiteEnvironment());
  //PAFProject* myProject = new PAFProject(new PAFPoDEnvironment(10));
  

  // (2) Define the data files to be used.
  // Select the files to be analysed and replicate the line below
  // as needed
  myProject->AddDataFile("You have to specify the input file");

  
  // (3) Define the name of the selector to be used
  // Modify the line below to specify the name of your selector
  // To create a new selector you may use PAF tools:
  // $ paf createselector SelectorName
  // Adding 2 selectors A and B
  myProject->AddSelectorPackage("SelA");
  myProject->AddSelectorPackage("SelB");
  
  // (4) Run the project. 
  // This will start the processing
  myProject->Run();
}
